apiVersion: v1
kind: Secret
metadata:
  name: sapi-smtp-runtime-damm-secret
type: Opaque
data:
  accAPI: aHR0cHM6Ly9ldTEuYW55cG9pbnQubXVsZXNvZnQuY29tL2FjY291bnRz
  hybridAPI: aHR0cHM6Ly9ldTEuYW55cG9pbnQubXVsZXNvZnQuY29tL2h5YnJpZC9hcGkvdjE=
  password: Sm9yZGlnYXJjaWEwMQ==
  username: Sm9yZGlHYXJjaWFfREFNTQ==
  organization: REFNTQ==
  environment: UFJP
  namespace: REFNTQ==
  servername: U0FQSS1TTVRQLURBTU0=
  AUTODISCOVERY_ID: MzIxNTQ=
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sapi-smtp-runtime-damm
spec:
  selector:
    matchLabels:
      app: sapi-smtp-runtime-damm
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: sapi-smtp-runtime-damm
    spec:
      containers:
      - name: sapi-smtp-runtime-damm
        image: 
        envFrom:
        - secretRef:
            name: sapi-smtp-runtime-damm-secret
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu:  1000m
            memory: 4096Mi
          requests:
            cpu:  500m
            memory: 2048Mi
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 30
            
---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: sapi-smtp-runtime-damm-autoescaler
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sapi-smtp-runtime-damm
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 3500Mi
        
---

apiVersion: v1
kind: Service
metadata:
  name: sapi-smtp-runtime-damm-service
spec:
  selector:
    app: sapi-smtp-runtime-damm
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
