apiPath: "/smtp/api/v1/*"

autodiscoveryID : ${AUTODISCOVERY_ID}

standard:
   port:
      external: "8081"
      internal: "8091"

smtp:
  host: "172.23.22.37"
  port: "25"
            
api_level-api_name:
 path: ""
 host: ""
 credentials:
  client_id: ""
  client_secret: ""
 endpoints:
  endpoint_name: ""