#%RAML 1.0
title: health
/health:
  get:
    body: {}
    responses:
      "200":
        body:
          application/json:
            type: | 
              {
                "title": "health-check Response",
                "type": "object",
                "properties": {
                  "message": {
                    "type": "string"
                  }
                }
              }
            example: 
              {
                "message": "health-check running"
              }
        